### ISSUE TITLE
Show version in page footer for frontend

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/DouglasDataCapturePlatform#170]
Frontend page footer should show one (or more) of
- version tag
- git commit id
- whether the code is dirty vs the commit

https://dev.to/eugenebabichenko/generating-pretty-version-strings-including-nightly-with-git-and-makefiles-48p3

**Comment by joshunrau** [comment]
c670800ed1cfacdb1e00428f3f03f92c1c77ddc8
