### ISSUE TITLE
Implement environment variables for branding customization

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/DouglasDataCapturePlatform#18]
- [x] logo file
- [x] "platform title"
- [ ] ADDMOREHERE

**Comment by joshunrau** [comment]
What do you think of doing this in a config file instead of environment variables? It is not straightforward to do this with environment variables.

**Comment by gdevenyi** [comment]
I'm fine with either. Just want to make things configurable.

**Comment by joshunrau** [comment]
Leaving this open to add more later

**Comment by joshunrau** [comment]
@gdevenyi this is done. Is it safe to close this now?

**Comment by gdevenyi** [comment]
Yup
