### ISSUE TITLE
Contact form for user feedback

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/DouglasDataCapturePlatform#25]

**Comment by gdevenyi** [comment]
The problem with an in-app form to do this, is, how do we then send the feedback? As of right now email integration is not in the spec of the code.

I think instead launching the local system's email client with pre-filled info (possible with the mailto: methods) would be a good solution

**Comment by joshunrau** [comment]
Marking this as to-do with the mailto template
